import 'package:flutter/material.dart';

const Color primaryColor = Color(0xFF592401);
const Color textSecondaryColor = Color(0xFF666F7B);
const Color textThirdaryColor = Color(0xFFBF7160);
const Color chipSelectColor = Color(0xFFEE906F);
const Color chipUnSelectColor = Color(0xFFF2ECEB);
const Color chipTextColor = Color(0xFF333333);
const Color toggleUnSelectBtnColor = Color(0xFFF3F4F6);
const Color toggleUnSelectTextColor = Color(0xFF9CA3AF);
const Color toggleSelectBtnColor = Color(0xFF8D6E63);
const Color toggleSelectTextColor = Color(0xFFFFFFFF);
const Color btnUnEableColor = Color(0xFFD4D4D4);
const Color btnEableColor = Color(0xFF592401);
const Color likeBtnColor = Color(0xFFD9626B);
const Color startBtnColor = Color(0xFFFBDB5A);
const Color loginTextColor = Color(0xFF2C2C2C);
const Color signupTextColor = Color(0xFF5D5D5D);
const Color boxShadowColor = Color(0xFF3A230F);
const Color btnTextColor = Colors.white;
const Color titleTextColor = Colors.black;
const Color errorTextColor = Color(0xFFFF2929);
const Color boxBackgroundColor = Color(0xFFF2ECEB);
