name: gdgs_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # flutter_native_splash: ^2.4.6
  flutter_native_splash: ^2.4.6
  flutter_rating_bar: ^4.0.1
  go_router: ^15.1.1

flutter_native_splash:
    color: "#FFFFFF"
    image: assets/image/logo.png

    android_12:
      color: "#FFFFFF"
      image: assets/image/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
  - family:  NavigationIcon
    fonts:
      - asset: assets/fonts/NavigationIcon.ttf
  - family:  Pretendard
    fonts:
      - asset: assets/fonts/PretendardVariable.ttf

  assets:
    - assets/image/
    - assets/image/food/
